project.clj
src/kixi/heimdall/components/database.clj
src/kixi/heimdall/handler.clj
src/kixi/heimdall/system.clj

based on kixi.hecuba, making sure we can connect to cassandra

cassandra database component working

---

resources/auth-conf-test.edn
src/kixi/heimdall/components/database.clj
src/kixi/heimdall/handler.clj
src/kixi/heimdall/refresh_token.clj
src/kixi/heimdall/user.clj
src/migrators/cassandra/201608101143_init.clj
test/kixi/heimdall/handler_test.clj

* new table in cassandra `refresh_tokens`
* create a token pair

refresh token

---

src/kixi/heimdall/handler.clj
src/kixi/heimdall/service.clj
src/kixi/heimdall/util.clj

more elegant file handling following suggestion by @otfrom

config file handling without using exceptions

---

src/kixi/heimdall/service.clj
test/kixi/heimdall/handler_test.clj

Try and prevent (un)signing steps from "exploding" or at least log a message when it does.

(Un)sign fns calls in try block

---

src/kixi/heimdall/components/database.clj
src/kixi/heimdall/group.clj
src/kixi/heimdall/handler.clj
src/kixi/heimdall/member.clj
src/kixi/heimdall/refresh_token.clj
src/kixi/heimdall/service.clj
src/kixi/heimdall/user.clj
src/migrators/cassandra/201609021113_init.clj
test/kixi/heimdall/handler_test.clj

* Added `groups` and `members` tables and fns
* Added a `/create-group` route
* Added a test for this route

Add user groups

---

project.clj
src/kixi/heimdall/handler.clj
src/kixi/heimdall/service.clj
src/kixi/heimdall/user.clj
test/kixi/heimdall/handler_test.clj

New route to validate password and sign up user.

---

docker-compose.yml
project.clj
resources/conf.edn
src/kixi/heimdall/bootstrap.clj
src/kixi/heimdall/components/logging.clj
src/kixi/heimdall/components/metrics.clj
src/kixi/heimdall/config.clj
src/kixi/heimdall/handler.clj
src/kixi/heimdall/system.clj
src/metrics/reporters/influxdb.clj
test/kixi/heimdall/handler_test.clj

integrate metrics and logging components.

add metrics and logging components

---

Dockerfile
README.md
circle.yml
heimdall.json.template
resources/conf.edn
scripts/deploy.sh
scripts/download-secrets.sh
src/kixi/heimdall.clj
src/kixi/heimdall/bootstrap.clj

pass in a parameter for bucket and region to retrieve the secrets from, make custom docker image a parameter, and a few misc fixes

some fixes to deployment to generalize heimdall to other stacks

---

project.clj

Also joplin back to main project instead of our fork, since PR has been included since.

upgrade comms to 0.1.11

---

README.md
project.clj
resources/joplin.edn
src/kixi/heimdall/components/database.clj
src/kixi/heimdall/handler.clj
src/kixi/heimdall/service.clj
src/seeds/cassandra.clj
test/kixi/heimdall/handler_test.clj

Modify the process for signing in

---

README.md
docker-compose.yml

The old docs were slightly wrong

Improve readme and upgrade docker ref

---

circle.yml
src/kixi/heimdall/user.clj
test/kixi/heimdall/integration/base.clj
test/kixi/heimdall/integration/user_test.clj

https://www.pivotaltracker.com/story/show/132826993

Add ability to change user passwords

---

src/kixi/heimdall/bootstrap.clj

Removed non-existant ns

---

scripts/download-secrets.sh

So we can see clearly if something went wrong

Add an error msg to the script

---

src/kixi/heimdall/service.clj
src/kixi/heimdall/user.clj
src/seeds/cassandra.clj

This is useful for development
As an aside, this PR took a while to do because of the groups bug. Contents of an auth token should be checked in a test, ideally.

Add a test group

---

resources/joplin.edn
src/seeds/cassandra.clj

Add a profile for seeding staging

---

resources/conf.edn

Needed to allow heimdall to configure inside the dev docker image

Changes to facilitate dev docker image

---

README.md
src/kixi/heimdall/group.clj
src/kixi/heimdall/service.clj

* get better feedback for repl group/user admin, or failing that an easy way to retrieve ids
* fix for token info which was broken after refreshing token

easier group user admin

---

README.md
project.clj
src/kixi/heimdall/group.clj
src/kixi/heimdall/schema.clj
src/kixi/heimdall/service.clj
src/migrators/cassandra/20170109125300_adding_self_groups.clj
test/kixi/heimdall/integration/auth_token_test.clj

* index for groups_by_users_and_type fixed to be unique
* test for auth_token so we don't have issues with wrong tokens
* small fix to find-by-user

Fixing self groups and auth token test

---

project.clj
scripts/run-dev.sh
scripts/run.sh

Adding to default jvm params

---

resources/conf.edn

we only give ourselves access to frankfurt region

eu-central-1 endpoint for dynamo

---

project.clj

* uncompressed messages
* exception handling

incremented kixi.comms

---

project.clj
resources/conf.edn
resources/joplin.edn
src/kixi/heimdall/components/database.clj

change dynamo table names

---

deployment/kixi.heimdall.json.template

kixi.heimdall instead of heimdall for marathon id, like prod

marathon id becomes kixi.heimdall

---

resources/conf.edn
resources/joplin.edn
src/kixi/heimdall/components/persistence.clj
src/kixi/heimdall/handler.clj
src/kixi/heimdall/invites.clj
src/kixi/heimdall/schema.clj
src/kixi/heimdall/service.clj
src/kixi/heimdall/system.clj
src/migrators/dynamodb/20170424153900_invites.clj
test/kixi/heimdall/handler_test.clj
test/kixi/heimdall/integration/invites_test.clj
test/kixi/heimdall/invites_test.clj

Implements invite code support into Heimdall

Invite codes

---

resources/conf.edn
resources/joplin.edn
src/kixi/heimdall/components/database.clj
src/kixi/heimdall/group.clj
src/kixi/heimdall/kaylee.clj
src/kixi/heimdall/service.clj
src/migrators/dynamodb/20170511141700_fix_groups.clj
test/kixi/heimdall/handler_test.clj
test/kixi/heimdall/integration/group_admin_test.clj

* Invite a new user
* Create a new group
* Add/remove users from groups
There was a bug with a gsindex on the groups table which is why there is
a fix migration in place.

Added Kaylee namespace with common support functions:

---

src/seeds/dynamodb.clj

We're on life support at the moment, this whole file needs re-vamping to use kaylee fns

Fix for broken seed fns

---

resources/conf.edn

**Fix metric disabling of kinesis**

Fix metric disabling of kinesis

---

deployment/production-marathon.json

**Change marathon deploy strategy for prod**

Change marathon deploy strategy for prod

---

.gitignore
src/kixi/heimdall/handler.clj
src/kixi/heimdall/util.clj
src/seeds/dynamodb.clj
test/kixi/heimdall/handler_test.clj
test/kixi/heimdall/integration/base.clj

* Use strings, not keywords
* Add tests

Fix group paging!

---

src/kixi/heimdall/kaylee.clj

The current one waits forever in a tight loop, this is never a good idea.

Upgrading kaylees wait-for function

---

src/kixi/heimdall/handler.clj
src/kixi/heimdall/service.clj
test/kixi/heimdall/handler_test.clj

Up until now we didn't have a way to get this. Mailer needs to know in order to resolve group emails

Add a way we can get the users in a group

---

src/kixi/heimdall/components/metrics.clj

Revert "Metrics as per datastore"

---

src/kixi/heimdall/kaylee.clj

**Ability to easily find invite information**
Handy for finding invite details from the REPL

Ability to easily find invite information

---

project.clj

Update to latest version of kixi.spec
